### ISSUE TITLE
Some Apps Not Working

### ISSUE THREAD

**Issue by iCrazeiOS** [JosephShenton/420#2]
Cercube5 doesn't install after signed. The only part of the output that could possibly be related is: 

> Can't Find CodeSignature Segment!

Same with Spotify++, but I get this error:

> No Enough CodeSignature Space! Length => Now: 512, Need: 6241

**Comment by JosephShenton** [comment]
Did you find the fix and cause for this issue?

**Comment by iCrazeiOS** [comment]
I have not found a fix. I closed it because I used zsign, and thought it worked, but that was because of AppSync. The apps still aren't working. Any clue?

**Comment by JosephShenton** [comment]
If you're trying to bulk resign apps, it could be because it's running out
of storage in /tmp

**Comment by iCrazeiOS** [comment]
Happens with bulk resign, and single.

**Comment by iCrazeiOS** [comment]
Used a different iPA somewhat worked. It now installs, but crashes in launch, and the file size is halved.

**Comment by iCrazeiOS** [comment]
Going to make a new Spotify++ iPA using the tweak dylib and optool

edit: still doesnt work

**Comment by JosephShenton** [comment]
The file size is small due to the program using zip level 9 meaning it is
smaller.

**Comment by iCrazeiOS** [comment]
Oh ok. I got the app to install, but just crashes on startup.

On 24 Nov 2019, at 9:25 pm, Joseph Shenton <notifications@github.com> wrote:

﻿The file size is small due to the program using zip level 9 meaning it is
smaller.
